/**
 * Jobhopper API
 * Jobhopper Swagger API Docs
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Bls model module.
 * @module model/Bls
 * @version v1
 */
class Bls {
    /**
     * Constructs a new <code>Bls</code>.
     * @alias module:model/Bls
     */
    constructor() { 
        
        Bls.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Bls</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Bls} obj Optional instance to populate.
     * @return {module:model/Bls} The populated <code>Bls</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Bls();

            if (data.hasOwnProperty('area_title')) {
                obj['area_title'] = ApiClient.convertToType(data['area_title'], 'String');
            }
            if (data.hasOwnProperty('soc_code')) {
                obj['soc_code'] = ApiClient.convertToType(data['soc_code'], 'String');
            }
            if (data.hasOwnProperty('soc_title')) {
                obj['soc_title'] = ApiClient.convertToType(data['soc_title'], 'String');
            }
            if (data.hasOwnProperty('hourly_mean_wage')) {
                obj['hourly_mean_wage'] = ApiClient.convertToType(data['hourly_mean_wage'], 'Number');
            }
            if (data.hasOwnProperty('annual_mean_wage')) {
                obj['annual_mean_wage'] = ApiClient.convertToType(data['annual_mean_wage'], 'Number');
            }
            if (data.hasOwnProperty('total_employment')) {
                obj['total_employment'] = ApiClient.convertToType(data['total_employment'], 'Number');
            }
            if (data.hasOwnProperty('soc_decimal_code')) {
                obj['soc_decimal_code'] = ApiClient.convertToType(data['soc_decimal_code'], 'String');
            }
            if (data.hasOwnProperty('file_year')) {
                obj['file_year'] = ApiClient.convertToType(data['file_year'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} area_title
 */
Bls.prototype['area_title'] = undefined;

/**
 * @member {String} soc_code
 */
Bls.prototype['soc_code'] = undefined;

/**
 * @member {String} soc_title
 */
Bls.prototype['soc_title'] = undefined;

/**
 * @member {Number} hourly_mean_wage
 */
Bls.prototype['hourly_mean_wage'] = undefined;

/**
 * @member {Number} annual_mean_wage
 */
Bls.prototype['annual_mean_wage'] = undefined;

/**
 * @member {Number} total_employment
 */
Bls.prototype['total_employment'] = undefined;

/**
 * @member {String} soc_decimal_code
 */
Bls.prototype['soc_decimal_code'] = undefined;

/**
 * @member {Number} file_year
 */
Bls.prototype['file_year'] = undefined;






export default Bls;

