/**
 * Jobhopper API
 * Jobhopper Swagger API Docs
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SocList model module.
 * @module model/SocList
 * @version v1
 */
class SocList {
    /**
     * Constructs a new <code>SocList</code>.
     * @alias module:model/SocList
     */
    constructor() { 
        
        SocList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SocList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SocList} obj Optional instance to populate.
     * @return {module:model/SocList} The populated <code>SocList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SocList();

            if (data.hasOwnProperty('soc_code')) {
                obj['soc_code'] = ApiClient.convertToType(data['soc_code'], 'String');
            }
            if (data.hasOwnProperty('soc_title')) {
                obj['soc_title'] = ApiClient.convertToType(data['soc_title'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} soc_code
 */
SocList.prototype['soc_code'] = undefined;

/**
 * @member {String} soc_title
 */
SocList.prototype['soc_title'] = undefined;






export default SocList;

