/**
 * Jobhopper API
 * Jobhopper Swagger API Docs
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SocList from './SocList';

/**
 * The SocLists model module.
 * @module model/SocLists
 * @version v1
 */
class SocLists {
    /**
     * Constructs a new <code>SocLists</code>.
     * @alias module:model/SocLists
     */
    constructor() { 
        
        SocLists.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SocLists</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SocLists} obj Optional instance to populate.
     * @return {module:model/SocLists} The populated <code>SocLists</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SocLists();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('next')) {
                obj['next'] = ApiClient.convertToType(data['next'], 'String');
            }
            if (data.hasOwnProperty('previous')) {
                obj['previous'] = ApiClient.convertToType(data['previous'], 'String');
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [SocList]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} count
 */
SocLists.prototype['count'] = undefined;

/**
 * @member {String} next
 */
SocLists.prototype['next'] = undefined;

/**
 * @member {String} previous
 */
SocLists.prototype['previous'] = undefined;

/**
 * @member {Array.<module:model/SocList>} results
 */
SocLists.prototype['results'] = undefined;






export default SocLists;

