# Generated by Django 3.1 on 2020-09-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OccupationTransitions",
            fields=[
                ("id", models.AutoField(primary_key=True, auto_created=True)),
                ("soc1", models.CharField(max_length=7)),
                ("soc2", models.CharField(max_length=7)),
                ("total_soc", models.BigIntegerField(null=True)),
                ("pi", models.DecimalField(decimal_places=10, max_digits=11, null=True)),
                ("occleaveshare", models.DecimalField(decimal_places=10, max_digits=11, null=True)),
            ],
        ),
    ]
