# Generated by Django 3.1 on 2020-08-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobclass',
            name='jobcode',
            field=models.IntegerField(default=0),
        ),
    ]
