# Generated by Django 3.1 on 2020-09-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_occupationtransitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupationtransitions',
            name='pi',
            field=models.CharField(max_length=50),
        ),
    ]
