# Generated by Django 3.1 on 2020-08-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_socs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socs',
            name='detailedOccupation',
            field=models.IntegerField(unique=True),
        ),
    ]
