# Generated by Django 3.1 on 2020-09-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_auto_20200909_1255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occupationtransitions",
            name="occleaveshare",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="occupationtransitions",
            name="pi",
            field=models.CharField(max_length=200),
        ),
    ]
