# Generated by Django 3.1 on 2020-10-14 00:33
from django.db import migrations, models



class Migration(migrations.Migration):
    """ 
    Update the model to have autofield to accomodate auto-incrementing ids and nullability on soc2 field. 
    Add code to migrate data from data migration script into django model. 
    """

    dependencies = [
        ('jobs', '0008_auto_20201006_AddStateData'),
    ]

    def forwards_func(apps, schema_editor):
        # alter fields for go-forward work
        migrations.AlterField('OccupationTransitions', 'id', models.AutoField(primary_key=True))
        migrations.AlterField('OccupationTransitions', 'soc2', models.CharField(max_length=7, null=True))

    def reverse_func(apps, schema_editor):
        # alter fields for backward migration.
        migrations.AlterField('OccupationTransitions', 'id', models.IntegerField(primary_key=True))
        migrations.AlterField('OccupationTransitions', 'soc2', models.CharField(max_length=7))

    operations = [
        migrations.RunPython(
            forwards_func, reverse_func
        ),
        migrations.RunSQL(
            [("insert into jobs_occupationtransitions (soc1, soc2, total_soc, pi, occleaveshare) select soc1, soc2, total_soc, pi, occleaveshare from occupation_transition")],
            [("DELETE FROM jobs_occupationtransitions")],
        ),
        
    ]
