# Generated by Django 3.1 on 2020-10-18 23:27

from django.db import migrations, models, connection
from data.scripts.sql_loader import load_bls_oes_to_sql

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20201013_2033'),
    ]

    def forwards_source_data(apps, schema_editor):
        with connection.schema_editor() as my_schema_editor:
            print(f" show db {my_schema_editor.connection.alias}")

        all_tables = connection.introspection.table_names()
        print("all tables available", all_tables)

        if 'bls_oes' not in all_tables:
            load_bls_oes_to_sql(year="2019", db="jobhopperdatabase")

        conn_info = str(schema_editor.connection.__dict__["connection"])
        print(conn_info)

        db_name = conn_info.split("dbname=")[1].split(" ")[0]

        print(db_name)
        print("done with forward load")

    def reverse_source_data(apps, schema_editor):
        print("removing source data")
        migrations.RunSQL([("DROP TABLE bls_oes;")])

    def forwards_null_fields(apps, schema_editor):
        print('Altering fields to allow null values')
        migrations.AlterField("BlsOesFakes",
                              "area_title",
                              models.CharField(max_length=100, null=True)),

        migrations.AlterField("BlsOesFakes",
                              "soc_code",
                              models.CharField(max_length=7, null=True)),

        migrations.AlterField("BlsOesFakes",
                              "soc_title",
                              models.CharField(max_length=200, null=True)),

        migrations.AlterField("BlsOesFakes",
                              "hourly_mean_wage",
                              models.DecimalField(decimal_places=2, max_digits=10, null=True)),

        migrations.AlterField("BlsOesFakes",
                              "annual_mean_wage",
                              models.DecimalField(decimal_places=2, max_digits=10, null=True)),

        migrations.AlterField("BlsOesFakes",
                              "total_employment",
                              models.BigIntegerField(null=True)),

        migrations.AlterField("BlsOesFakes",
                              "soc_decimal_code",
                              models.CharField(max_length=200, null=True))

    def reverse_null_fields(apps, schema_editor):
        migrations.AlterField("BlsOesFakes",
                              "area_title",
                              models.CharField(max_length=10)),

        migrations.AlterField("BlsOesFakes",
                              "soc_code",
                              models.CharField(max_length=7)),

        migrations.AlterField("BlsOesFakes",
                              "soc_title",
                              models.CharField(max_length=200)),

        migrations.AlterField("BlsOesFakes",
                              "hourly_mean_wage",
                              models.DecimalField(decimal_places=2, max_digits=10)),

        migrations.AlterField("BlsOesFakes",
                              "annual_mean_wage",
                              models.DecimalField(decimal_places=2, max_digits=10)),

        migrations.AlterField("BlsOesFakes",
                              "total_employment",
                              models.BigIntegerField()),

        migrations.AlterField("BlsOesFakes",
                              "soc_decimal_code",
                              models.CharField(max_length=200))

    operations = [
        migrations.CreateModel(
            name='BlsOes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('area_title', models.CharField(max_length=255, null=True)),
                ('soc_code', models.CharField(max_length=10, null=True)),
                ('soc_title', models.CharField(max_length=255, null=True)),
                ('hourly_mean_wage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('annual_mean_wage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_employment', models.BigIntegerField(null=True)),
                ('soc_decimal_code', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RunPython(forwards_source_data, reverse_source_data),
        migrations.RunSQL(
            [
                (
                    """
                    INSERT INTO jobs_blsoes (area_title, soc_code, soc_title, hourly_mean_wage, 
                        annual_mean_wage, total_employment, soc_decimal_code) 
                    SELECT area_title, soc_code, soc_title, hourly_mean_wage, 
                        annual_mean_wage, total_employment, soc_decimal_code
                    FROM bls_oes;
                    """
                )
            ],
            [("DELETE FROM jobs_blsoes;")],
        ),
    ]
