# Generated by Django 3.1 on 2020-10-24 21:45

from django.db import migrations, models
from data.scripts.sql_loader import load_bls_oes_to_sql

class Migration(migrations.Migration):
    """
    Load BLS OES data for the prototype into the jobs_blsoes database (BlsOes model, created in the previous migration)
    """
    dependencies = [
        ('jobs', '0010_blsoes'),
    ]

    def forwards_source_data(apps, schema_editor):
        load_bls_oes_to_sql(
            start_year=2017,
            end_year=2019,
            table_name="jobs_blsoes")

        print("Done with forward load")

    def reverse_source_data(apps, schema_editor):
        print("Removing source data")
        migrations.RunSQL([("DELETE FROM jobs_blsoes;")])

    operations = [
        migrations.RunPython(forwards_source_data, reverse_source_data)
    ]
