/**
 * Jobhopper API
 * Jobhopper Swagger API Docs
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JobsApi);
  }
}(this, function(expect, JobsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JobsApi.OccupationTransition();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OccupationTransition', function() {
    it('should create an instance of OccupationTransition', function() {
      // uncomment below and update the code to test OccupationTransition
      //var instane = new JobsApi.OccupationTransition();
      //expect(instance).to.be.a(JobsApi.OccupationTransition);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new JobsApi.OccupationTransition();
      //expect(instance).to.be();
    });

    it('should have the property soc1 (base name: "soc1")', function() {
      // uncomment below and update the code to test the property soc1
      //var instane = new JobsApi.OccupationTransition();
      //expect(instance).to.be();
    });

    it('should have the property soc2 (base name: "soc2")', function() {
      // uncomment below and update the code to test the property soc2
      //var instane = new JobsApi.OccupationTransition();
      //expect(instance).to.be();
    });

    it('should have the property totalSoc (base name: "total_soc")', function() {
      // uncomment below and update the code to test the property totalSoc
      //var instane = new JobsApi.OccupationTransition();
      //expect(instance).to.be();
    });

    it('should have the property pi (base name: "pi")', function() {
      // uncomment below and update the code to test the property pi
      //var instane = new JobsApi.OccupationTransition();
      //expect(instance).to.be();
    });

    it('should have the property occleaveshare (base name: "occleaveshare")', function() {
      // uncomment below and update the code to test the property occleaveshare
      //var instane = new JobsApi.OccupationTransition();
      //expect(instance).to.be();
    });

  });

}));
