#!/bin/sh

# Build production images

cd $(dirname $0)

./compose/prod-builder build frontend api

# The gateway image depends on the frontend image so build it after.
./compose/prod-builder build gateway