#!/bin/sh

# Start the production deployment on a swarm manager node.

cd $(dirname $0)

if [ -z "$SECRET_KEY" ]; then
  echo "Please specify SECRET_KEY environment variable"
  exit 1
fi

if [ -z "$DOMAIN" ]; then
  echo "Please specify DOMAIN environment variable"
  exit 1
fi

docker stack rm jobhopper-prod
docker stack deploy \
  -c compose/common.yml \
  -c compose/deploy.prod.yml \
  jobhopper-prod