# Generated by Django 3.1 on 2020-08-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200818_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOCs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailedOccupation', models.CharField(max_length=7, unique=True)),
                ('detailName', models.CharField(max_length=400)),
                ('majorGroup', models.CharField(max_length=7)),
                ('minorGroup', models.CharField(max_length=7)),
                ('broadGroup', models.CharField(max_length=7)),
                ('majorName', models.CharField(max_length=200)),
                ('minorName', models.CharField(max_length=200)),
                ('broadName', models.CharField(max_length=200)),
            ],
        ),
    ]
