# Generated by Django 3.1 on 2020-10-24 21:45

from django.db import migrations, models, connection
from data.scripts.sql_loader import load_bls_oes_to_sql

import logging

log = logging.getLogger()


class Migration(migrations.Migration):
    """
    Load BLS OES data for the prototype into the jobs_blsoes database (BlsOes model, created in the previous migration)
    """
    dependencies = [
        ('jobs', '0012_socdescription'),
    ]

    def forwards_source_data(apps, schema_editor):
        conn_info = str(schema_editor.connection.__dict__["connection"])
        log.info(f"0013 Connection info: {conn_info}")

        db_name = conn_info.split("dbname=")[1].split(" ")[0]
        log.info(f"0013 DB name: {db_name}")

        load_bls_oes_to_sql(
            start_year=2018,
            end_year=2019,
            db=db_name,
            table_name=None,
            soc_table_name="jobs_socdescription",
            transitions_file_path="data/occupation_transitions_public_data_set.csv")

        log.info("Done with forward load for jobs_socdescription")

    def reverse_source_data(apps, schema_editor):
        print("Removing source data")
        migrations.RunSQL([("DELETE FROM jobs_socdescription;")])

    operations = [
        migrations.RunPython(forwards_source_data, reverse_source_data)
    ]
